### PR TITLE
Sort heatmap topics by topic number instead of alphabetically

### PR DESCRIPTION
**Pull request by melaniewalsh**
Just a suggestion but I've noticed that sorting the heatmap topics by topic number rather than alphabetically can be helpful

### CODE REVIEW

**Comment by maria-antoniak** [comment]
Added using a different method.

**Comment by melaniewalsh** [comment]
Just a quick q. How do you sort the heatmap by topic number instead of alphabetically? I'd love to include it in my course materials!

**Comment by maria-antoniak** [comment]
Added the topic number to the title. :) 

Might need more refinement; let me know!

**Comment by melaniewalsh** [comment]
Hmmm I can't see where the topic number is being added to the title? Sorry if I'm being dense!

**Comment by maria-antoniak** [comment]
I forgot to push the change! Thanks for letting me know. 😅

This update should now be available by pulling the repo and will be included in the next version.

**Comment by melaniewalsh** [comment]
Sure thing! I checked it out and it looks good :D

**Pull request closed without merging**
